{% set version = "0.3.2" %}
{% set name = "dry-attr" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/attr/attr-{{ version }}.tar.gz
  sha256: 1ceebca768181cdcce9827611b1d728e592be5d293911539ea3d0b0bfa1146f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - attr
    - dry_attr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/denis-ryzhkov/attr
  summary: Simple decorator to set attributes of target function or class in a DRY way.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - denis-ryzhkov
    - iamthebot
